

on:
  issue_comment:
    types: [created]
name: Automatic Merge
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && (contains(github.event.comment.body, '/rebase') || contains(github.event.comment.body, '/merge'))
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: zacsweers/rebase@v2.0.1
      env:
        GITHUB_TOKEN: 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
        GITHUB_COMMENT_ACTION: hide
